apiVersion: v1
kind: Service
metadata:
  name: alertmanager-cluster
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Alertmanager-cluster"
spec:
  clusterIP: None
  ports:
  - port: 9094
    targetPort: 9094
  selector:
    k8s-app: alertmanager 
