#注意，如果是高可用方案，pv应该需要创建两个，因为一个pv只能供一个pvc使用，且在prometheus的高可用方案中，是需要有两套互相独立的实例
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
labels:
  k8s-app: prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data    