kind: Service
apiVersion: v1
metadata:
  labels: 
    kubernetes.io/name: "Prometheus"
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
  name: prometheus
  namespace: kube-system
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30003
  selector:
    k8s-app: prometheus    